<?php
/**
 *
 * This file is part of the phpBB Forum Software package.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

/**
 * DO NOT CHANGE
 */
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'HELP_BBCODE_BLOCK_IMAGES'	=> 'Mostrando imagens nos posts',
	'HELP_BBCODE_BLOCK_INTRO'	=> 'Introdução',
	'HELP_BBCODE_BLOCK_LINKS'	=> 'Criando links',
	'HELP_BBCODE_BLOCK_LISTS'	=> 'Gerando listas',
	'HELP_BBCODE_BLOCK_OTHERS'	=> 'Outros assuntos',
	'HELP_BBCODE_BLOCK_QUOTES'	=> 'Citação e saída de texto de largura fixa',
	'HELP_BBCODE_BLOCK_TEXT'	=> 'Formatação de texto',

	'HELP_BBCODE_IMAGES_ATTACHMENT_ANSWER'	=> 'Os anexos agora podem ser colocados em qualquer parte de um post usando o novo BBCode <strong>[attachment=][/attachment]</strong> se a funcionalidade de anexos tiver sido ativada por um administrador do forum e Se você tiver as permissões apropriadas para criar anexos. Dentro da tela de lançamento é uma caixa drop-down (respectivamente um botão) para colocar anexos inline.',
	'HELP_BBCODE_IMAGES_ATTACHMENT_QUESTION'	=> 'Adicionando anexos a uma postagem',
	'HELP_BBCODE_IMAGES_BASIC_ANSWER'	=> 'phpBB BBCode incorpora uma tag para incluir imagens em suas postagens. Duas coisas muito importantes a serem lembradas ao usar essa tag são: muitos usuários não apreciam muitas imagens sendo exibidas em posts e, em segundo lugar, a imagem que você exibe já deve estar disponível na internet (não pode existir apenas no seu computador, Executar um servidor web!). Para exibir uma imagem, você deve rodear a URL que aponta para a imagem com <strong>[img][/img]</strong> tags. Por exemplo:<br /><br /><strong>[img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img]</strong><br /><br />Conforme mencionado na seção de URL acima, você pode envolver uma imagem em uma tag <strong>[url][/url]</strong> se desejar, por exemplo .<br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/img][/url]</strong><br /><br /> Gerava:<br /><br /><a href="https://www.phpbb.com/"><img src="https://www.phpbb.com/theme/images/logos/blue/160x52.png" alt="" /></a>',
	'HELP_BBCODE_IMAGES_BASIC_QUESTION'	=> 'Adicionando uma imagem a uma postagem',

	'HELP_BBCODE_INTRO_BBCODE_ANSWER'	=> 'BBCode é uma implementação especial de HTML. Se você pode realmente usar o BBCode em suas postagens no fórum é determinado pelo administrador. Além disso, você pode desabilitar o BBCode por post via o formulário de lançamento. BBCode em si é semelhante em estilo ao HTML, as tags são colocadas entre colchetes [e] em vez de &lt; E &gt; E oferece maior controle sobre o que e como algo é exibido. Dependendo do modelo que você está usando, você pode achar adicionando BBCode para suas postagens é feito muito mais fácil através de uma interface clicável acima da área de mensagem no formulário de postagem. Mesmo com isso você pode encontrar o seguinte guia útil.',
	'HELP_BBCODE_INTRO_BBCODE_QUESTION'	=> 'O que é BBCode?',

	'HELP_BBCODE_LINKS_BASIC_ANSWER'	=> 'phpBB O BBCode suporta várias maneiras de criar URIs (Indicadores de Recursos Uniformes) mais conhecidos como URLs.<ul><li>O primeiro destes usa o <strong>[url=][/url]</strong>  o que você digitar após o sinal = fará com que o conteúdo dessa tag aja como um URL. Por exemplo, para criar um link para phpBB.com, você pode usar: <br /><br /><strong>[url=https://www.phpbb.com/]</strong>Visite o phpBB!<strong>[/url]</strong><br /><br />Isso gerava o seguinte link, <a href="https://www.phpbb.com/">Visit phpBB!</a>Visite o phpBB! </a> Por favor note que o link é aberto Na mesma janela ou em uma nova janela, dependendo das preferências do navegador dos usuários.</li><li>Se você quiser que o URL seja exibido como o link, você pode fazer isso simplesmente usando: <br /><br /><strong>[url]</strong>https://www.phpbb.com/<strong>[/url]</strong><br /><br />Isso gerava o seguinte link, <a href="https://www.phpbb.com/">https://www.phpbb.com/</a></li><li>Além disso, o phpBB possui algo chamado <i>Magic Links</i>, Transformar qualquer URL sintaticamente correto em um link sem que você precise especificar quaisquer tags ou até mesmo o https: // principal. Por exemplo, digitar www.phpbb.com na sua mensagem irá automaticamente levar a <a href="https://www.phpbb.com/">www.phpbb.com</a> a ser emitido quando visualizar a mensagem.</li><li>A mesma coisa se aplica igualmente aos endereços de e-mail, você pode especificar um endereço explicitamente, por exemplo:<br /><br /><strong>[email]</strong>no.one@domain.adr<strong>[/email]</strong><br /><br />que exibirá  <a href="mailto:no.one@domain.adr">no.one@domain.adr</a> ou Você pode simplesmente digitar no.one@domain.adr  em sua mensagem e ele será convertido automaticamente quando você visualiza.</li></ul>Como com todas as tags BBCode, você pode envolver URLs em torno de qualquer uma das outras tags, como <strong>[img][/img]</strong> (ver entrada seguinte), <strong>[b][/b]</strong>, etc. Como com as etiquetas de formatação, Correta ordem de abertura e fechamento está seguindo, por exemplo: <br /><br /><strong>[url=https://www.phpbb.com/][img]</strong>https://www.phpbb.com/theme/images/logos/blue/160x52.png<strong>[/url][/img]</strong><br /><br />é <span style="text-decoration: underline">não</span>  correto, o que pode levar a que sua postagem seja excluída.',
	'HELP_BBCODE_LINKS_BASIC_QUESTION'	=> 'Vinculação a outro site',

	'HELP_BBCODE_LISTS_ORDERER_ANSWER'	=> 'O segundo tipo de lista, uma lista ordenada, dá-lhe o controle sobre o que é saída antes de cada item. Para criar uma lista ordenada, use <strong>[list=1][/list]</strong>  para criar uma lista numerada ou <strong>[list=a][/list]</strong> para uma lista alfabética. Tal como acontece com a lista não ordenada, os itens são especificados usando  <strong>[*]</strong>. Por exemplo: <br /><br /><strong>[list=1]</strong><br /><strong>[*]</strong>Vai a uma loja<br /><strong>[*]</strong>Compre um novo computador <br /><strong>[*]</strong> quando ele falhar<br /><strong>[/list]</strong><br /><br />Irá gerar o seguinte:<ol style="list-style-type: decimal;"><li>Vai a uma loja</li><li>comprar um novo computador</li><li>quando ele falha</li></ol>Considerando que para uma lista alfabética você usaria:<br /><br /><strong>[list=a]</strong><br /><strong>[*]</strong>A primeira resposta possível <br /><strong>[*]</strong> A segunda resposta possível<br /><strong>[*]</strong> A terceira resposta possível <br /><strong>[/list]</strong><br /><br />giving<ol style="list-style-type: lower-alpha"><li>A primeira resposta possível</li><li>O segunda resposta possível</li><li>A terceira resposta possível </li></ol>',
	'HELP_BBCODE_LISTS_ORDERER_QUESTION'	=> 'Criando uma lista ordenada',
	'HELP_BBCODE_LISTS_UNORDERER_ANSWER'	=> 'BBCode suporta dois tipos de listas, desordenadas e ordenadas. Eles são essencialmente os mesmos que seus equivalentes HTML. Uma lista desordenada emite cada item da lista sequencialmente um após o outro, cada um com um caractere de marcador. Para criar uma lista desordenada, use <strong>[list][/list]</strong>e defina cada item na lista usando <strong>[*]</strong>. Por exemplo, para listar suas cores favoritas que você poderia usar: <br /><br /><strong>[list]</strong><br /><strong>[*]</strong>Vermelho<br /><strong>[*]</strong>Azul<br /><strong>[*]</strong>Amarelo<br /><strong>[/list]</strong><br /><br />Isso geraria A seguinte lista:<ul><li>Vermelho</li><li>Azul</li><li>Amarelo</li></ul><br />Como alternativa, você pode especificar o estilo de listagem usando <strong>[list=disc][/list]</strong>, <strong>[list=circle][/list]</strong>, or <strong>[list=square][/list]</strong>.',
	'HELP_BBCODE_LISTS_UNORDERER_QUESTION'	=> 'Criando uma lista desordenada',

	'HELP_BBCODE_OTHERS_CUSTOM_ANSWER'	=> 'Se você é um administrador nesta placa e tem as permissões apropriadas, você pode adicionar mais BBCodes através da seção Custom BBCodes.',
	'HELP_BBCODE_OTHERS_CUSTOM_QUESTION'	=> 'Posso adicionar minhas próprias tags?',

	'HELP_BBCODE_QUOTES_CODE_ANSWER'	=> 'Se você quiser produzir um pedaço de código ou de fato qualquer coisa que exija uma largura fixa, e.g. O tipo de letra Courier deve incluir o texto em tags  <strong>[code][/code]</strong> tags, e.g.<br /><br /><strong>[code]</strong>echo &quot;Este é algum code&quot;;<strong>[/code]</strong><br /><br />Todas as formatações usadas dentro de tags  <strong>[code][/code]</strong> são mantidas quando você a vê mais tarde. A sintaxe de sintaxe de PHP pode ser ativada usando <strong>[code=php][/code]</strong> e é recomendada ao exibir amostras de código PHP, pois melhora a legibilidade.',
	'HELP_BBCODE_QUOTES_CODE_QUESTION'	=> 'Código de saída ou dados de largura fixa',
	'HELP_BBCODE_QUOTES_TEXT_ANSWER'	=> 'Existem duas maneiras de citar texto, com uma referência ou sem.<ul><liQuando você utiliza a função Citação para responder a uma postagem na placa, você deve notar que o texto da postagem é adicionado Para a janela de mensagem incluída num bloco<strong>[quote=&quot;&quot;][/quote]</strong> Este método permite-lhe citar com uma referência a uma pessoa ou qualquer outra coisa que você escolher para colocar! Por exemplo, para citar um pedaço de texto, o Sr. Blobby escreveu que você entraria::<br /><br /><strong>[quote=&quot;Mr. Blobby&quot;]</strong>O texto que o Sr. Blobby escreveu iria aqui <strong>[/quote]</strong><br /><br />A saída resultante adicionará automaticamente" Mr. Blobby escreveu:&quot; antes do texto real. Lembre-se que <strong>must</strong> incluir as aspas &quot;&quot; em torno do nome que você está citando, eles não são opcionais.</li><li>O segundo método permite citar cegamente algo. Para utilizar isso, coloque o texto nas tags <strong>[quote][/quote]</strong> Quando você visualiza a mensagem, ele simplesmente mostrará o texto dentro de um bloco de cotação.</li></ul>',
	'HELP_BBCODE_QUOTES_TEXT_QUESTION'	=> 'Citar texto nas respostas',

	'HELP_BBCODE_TEXT_BASIC_ANSWER'	=> 'BBCode inclui tags para permitir que você mude rapidamente o estilo básico do seu texto. Isto é conseguido das seguintes maneiras: <ul><li>Para fazer uma parte de texto em negrito, coloque-a em <strong>[b][/b]</strong>, e.g. <br /><br /><strong>[b]</strong>Olá<strong>[/b]</strong><br /><br />se tornará  <strong>Olá</strong></li><li> Para o sublinhado, use <strong>[u][/u]</strong>,  por exemplo:<br /><br /><strong>[u]</strong>Bom dia<strong>[/u]</strong><br /><br />becomes <span style="text-decoration: underline">Bom dia</span></li><li>Para itálico texto use <strong>[i][/i]</strong>, por exemplo:<br /><br />Isto é  <strong>[i]</strong>Ótimo!<strong>[/i]</strong><br /><br />daria Isto é<i>Ótimo! </i></li></ul>',
	'HELP_BBCODE_TEXT_BASIC_QUESTION'	=> 'Como criar texto em negrito, itálico e sublinhado',
	'HELP_BBCODE_TEXT_COLOR_ANSWER'	=> 'Para alterar a cor ou o tamanho do seu texto, as seguintes tags podem ser usadas. Lembre-se de que a aparência da saída dependerá do navegador e do sistema do espectador: <ul><li>A alteração da cor do texto é obtida por meio de um <strong>[color=][/color]</strong>. Você pode especificar um nome de cor reconhecido (por exemplo, vermelho, azul, amarelo, etc.) ou a alternativa de tripleto hexadecimal, e.g. #FFFFFF, #000000. Por exemplo, para criar texto em vermelho, você pode usar:<br /><br /><strong>[color=red]</strong>Olá!<strong>[/color]</strong><br /><br />or<br /><br /><strong>[color=#FF0000]</strong>Olá!<strong>[/color]</strong><br /><br />Ambos irão <span style="color:red">Olá!</span></li><li>Alterar o tamanho do texto é conseguido de forma semelhante usando <strong>[size=][/size]</strong>. Essa tag depende do modelo selecionado pelo usuário, mas o formato recomendado é um valor numérico que representa o tamanho do texto em porcentagem, começando em 20 (muito pequeno) até 200 (muito grande) por padrão. Por exemplo:<br /><br /><strong>[size=30]</strong>SMALL<strong>[/size]</strong><br /><br />Geralmente será:<span style="font-size:30%;">SMALL</span><br /><br />whereas:<br /><br /><strong>[size=200]</strong>HUGE!<strong>[/size]</strong><br /><br /> será <span style="font-size:200%;">HUGE!</span></li></ul>',
	'HELP_BBCODE_TEXT_COLOR_QUESTION'	=> 'Como alterar a cor ou o tamanho do texto',
	'HELP_BBCODE_TEXT_COMBINE_ANSWER'	=> 'Sim, claro que você pode, por exemplo, para chamar a atenção de alguém que você pode escrever:<br /><br /><strong>[size=200][color=red][b]</strong>OLHE PARA MIM!<strong>[/b][/color][/size]</strong><br /><br />Isso iria sair <span style="color:red;font-size:200%;"><strong>OLHE PARA MIM!</strong></span><br /><br /> Nós não recomendamos que você produza muitos textos parecidos com isto! Lembre-se que cabe a você, o cartaz, garantir que as tags são fechadas corretamente. Por exemplo, o seguinte está incorreto:<br /><br /><strong>[b][u]</strong>Isso é errado<strong>[/b][/u]</strong>',
	'HELP_BBCODE_TEXT_COMBINE_QUESTION'	=> 'Posso combinar tags de formatação?',
));